// @generated by amari-discovery catalog generator — do not edit.

/// Embedded catalog manifest (split layout).
pub static MANIFEST_JSON: &str = include_str!("manifest.json");

/// Embedded per-crate JSON bodies in manifest order.
pub static CRATE_JSON: &[(&str, &str)] = &[
    ("amari", include_str!("crates/amari.json")),
    ("amari-automata", include_str!("crates/amari-automata.json")),
    ("amari-calculus", include_str!("crates/amari-calculus.json")),
    ("amari-cgt", include_str!("crates/amari-cgt.json")),
    ("amari-core", include_str!("crates/amari-core.json")),
    ("amari-discovery-macros", include_str!("crates/amari-discovery-macros.json")),
    ("amari-dual", include_str!("crates/amari-dual.json")),
    ("amari-dynamics", include_str!("crates/amari-dynamics.json")),
    ("amari-enumerative", include_str!("crates/amari-enumerative.json")),
    ("amari-flynn", include_str!("crates/amari-flynn.json")),
    ("amari-flynn-macros", include_str!("crates/amari-flynn-macros.json")),
    ("amari-functional", include_str!("crates/amari-functional.json")),
    ("amari-fusion", include_str!("crates/amari-fusion.json")),
    ("amari-gpu", include_str!("crates/amari-gpu.json")),
    ("amari-holographic", include_str!("crates/amari-holographic.json")),
    ("amari-info-geom", include_str!("crates/amari-info-geom.json")),
    ("amari-measure", include_str!("crates/amari-measure.json")),
    ("amari-network", include_str!("crates/amari-network.json")),
    ("amari-optimization", include_str!("crates/amari-optimization.json")),
    ("amari-probabilistic", include_str!("crates/amari-probabilistic.json")),
    ("amari-relativistic", include_str!("crates/amari-relativistic.json")),
    ("amari-rewrite", include_str!("crates/amari-rewrite.json")),
    ("amari-rewrite-macros", include_str!("crates/amari-rewrite-macros.json")),
    ("amari-surcomplex", include_str!("crates/amari-surcomplex.json")),
    ("amari-surreal", include_str!("crates/amari-surreal.json")),
    ("amari-topology", include_str!("crates/amari-topology.json")),
    ("amari-tropical", include_str!("crates/amari-tropical.json")),
    ("amari-wasm", include_str!("crates/amari-wasm.json")),
];
