// SPDX-License-Identifier: MIT OR Apache-2.0
//! Per-crate split layout for the structural catalog (CORE-CAT1).
//!
//! The checked-in catalog is stored as `catalog/manifest.json` plus one
//! canonical JSON file per crate under `catalog/crates/`. The manifest
//! carries every non-crate field of [`StructuralCatalog`] (including
//! `content_hash` and cross-crate dependency edges) and the ordered list
//! of crate files.
//!
//! [`split_catalog`] and [`compose_structural`] are exact inverses:
//! composing the split files of a catalog reproduces the canonical
//! serialization of that catalog byte for byte, so the `content_hash`
//! recipe and all validation semantics are unchanged from the former
//! monolithic `generated.json` layout.
//!
//! The split exists to eliminate merge conflicts between pull requests
//! that touch different crates: only `crates/<name>.json` and the
//! manifest change when one crate's public surface changes.

use serde::{Deserialize, Serialize};

use crate::{DiscoveryResult, StructuralCatalog};

use super::model::{CrateRecord, DependencyEdgeRecord, ProbeDescriptor, WasmSurfaceRef};

/// Reference to one per-crate JSON file in the split layout.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct CrateFileEntry {
    /// Cargo package name of the referenced crate.
    pub name: String,
    /// Repository-relative file path of the crate's JSON file.
    pub file: String,
}

/// Aggregate counts carried by the manifest for quick inspection.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct SplitTotals {
    /// Total number of structurally indexed crates.
    pub crates: usize,
    /// Total number of catalog items across all crates.
    pub items: usize,
    /// Total number of cross-crate dependency edges.
    pub dependency_edges: usize,
}

/// Manifest of the split catalog layout.
///
/// Holds every [`StructuralCatalog`] field except `crates`, plus the
/// ordered per-crate file references and totals.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct CatalogManifest {
    /// Structural catalog schema version (mirrors the composed catalog).
    pub schema_version: u32,
    /// Amari release version represented by the snapshot.
    pub version: String,
    /// Human-readable scope note for the snapshot.
    pub description: String,
    /// Deterministic SHA-256 of the canonical composed catalog bytes
    /// (excluding the field itself), exactly as in the monolithic layout.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_hash: Option<String>,
    /// Declarative probe descriptors (mirrors the composed catalog).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub probe_descriptors: Vec<ProbeDescriptor>,
    /// WASM surface summary (mirrors the composed catalog).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wasm_surface: Option<WasmSurfaceRef>,
    /// Cross-crate dependency edges (mirrors the composed catalog).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependency_edges: Vec<DependencyEdgeRecord>,
    /// Ordered per-crate file references; composition order.
    pub crates: Vec<CrateFileEntry>,
    /// Aggregate counts for quick inspection.
    pub totals: SplitTotals,
}

/// Serializes a manifest to canonical bytes (pretty + trailing newline).
pub fn manifest_bytes(manifest: &CatalogManifest) -> DiscoveryResult<Vec<u8>> {
    let mut bytes = serde_json::to_vec_pretty(manifest)
        .map_err(|error| crate::DiscoveryError::CatalogCorruption(error.to_string()))?;
    bytes.push(b'\n');
    Ok(bytes)
}

/// Renders the generated compile-time include table (`catalog/index.rs`)
/// for a manifest. Shared by the generator example and the drift verifier
/// so verification covers the loader artifact too.
pub fn render_index_rs(manifest: &CatalogManifest) -> String {
    let mut index = String::from(
        "// @generated by amari-discovery catalog generator — do not edit.\n\n/// Embedded catalog manifest (split layout).\npub static MANIFEST_JSON: &str = include_str!(\"manifest.json\");\n\n/// Embedded per-crate JSON bodies in manifest order.\npub static CRATE_JSON: &[(&str, &str)] = &[\n",
    );
    for entry in &manifest.crates {
        index.push_str(&format!(
            "    (\"{}\", include_str!(\"crates/{}.json\")),\n",
            entry.name, entry.name
        ));
    }
    index.push_str("];\n");
    index
}

/// Splits a generated catalog into its manifest and per-crate JSON bodies.
///
/// Each body is the canonical pretty-printed serialization of one
/// [`super::model::CrateRecord`] plus a trailing newline.
pub fn split_catalog(
    catalog: &StructuralCatalog,
) -> DiscoveryResult<(CatalogManifest, Vec<(String, String)>)> {
    let mut bodies = Vec::with_capacity(catalog.crates.len());
    let mut entries = Vec::with_capacity(catalog.crates.len());
    for record in &catalog.crates {
        let mut bytes = serde_json::to_vec_pretty(record)
            .map_err(|error| crate::DiscoveryError::CatalogCorruption(error.to_string()))?;
        bytes.push(b'\n');
        bodies.push((
            record.name.clone(),
            String::from_utf8(bytes)
                .map_err(|error| crate::DiscoveryError::CatalogCorruption(error.to_string()))?,
        ));
        entries.push(CrateFileEntry {
            name: record.name.clone(),
            file: format!("crates/{}.json", record.name),
        });
    }

    let manifest = CatalogManifest {
        schema_version: catalog.schema_version,
        version: catalog.version.clone(),
        description: catalog.description.clone(),
        content_hash: catalog.content_hash.clone(),
        probe_descriptors: catalog.probe_descriptors.clone(),
        wasm_surface: catalog.wasm_surface.clone(),
        dependency_edges: catalog.dependency_edges.clone(),
        crates: entries,
        totals: SplitTotals {
            crates: catalog.crates.len(),
            items: catalog.crates.iter().map(|c| c.items.len()).sum(),
            dependency_edges: catalog.dependency_edges.len(),
        },
    };

    Ok((manifest, bodies))
}

/// Composes a [`StructuralCatalog`] from split-layout sources.
///
/// `crate_bodies` must contain exactly the bodies referenced by the
/// manifest, identified by crate name; order is taken from the manifest.
/// The composed value serializes canonically to the same bytes as the
/// catalog that was split.
///
/// # Errors
///
/// Returns [`crate::DiscoveryError::CatalogCorruption`] when the manifest
/// is malformed, a referenced body is missing or duplicated, a body's name
/// does not match its reference, or a body fails to parse.
pub fn compose_structural(
    manifest_json: &str,
    crate_bodies: &[(&str, &str)],
) -> DiscoveryResult<StructuralCatalog> {
    use std::collections::HashMap;

    let manifest: CatalogManifest = serde_json::from_str(manifest_json).map_err(|error| {
        crate::DiscoveryError::CatalogCorruption(format!("invalid catalog manifest JSON: {error}"))
    })?;

    let mut by_name: HashMap<&str, &str> = HashMap::with_capacity(crate_bodies.len());
    for (name, body) in crate_bodies {
        if by_name.insert(name, body).is_some() {
            return Err(crate::DiscoveryError::CatalogCorruption(format!(
                "duplicate crate body for {name}"
            )));
        }
    }

    let mut crates = Vec::with_capacity(manifest.crates.len());
    let mut consumed: std::collections::HashSet<&str> =
        std::collections::HashSet::with_capacity(manifest.crates.len());
    for entry in &manifest.crates {
        if !consumed.insert(entry.name.as_str()) {
            return Err(crate::DiscoveryError::CatalogCorruption(format!(
                "duplicate manifest reference for crate {}",
                entry.name
            )));
        }
        let body = by_name.get(entry.name.as_str()).copied().ok_or_else(|| {
            crate::DiscoveryError::CatalogCorruption(format!(
                "missing crate body for {} (expected at {})",
                entry.name, entry.file
            ))
        })?;
        let record: CrateRecord = serde_json::from_str(body).map_err(|error| {
            crate::DiscoveryError::CatalogCorruption(format!(
                "invalid crate body for {}: {error}",
                entry.name
            ))
        })?;
        if record.name != entry.name {
            return Err(crate::DiscoveryError::CatalogCorruption(format!(
                "crate body name {} does not match manifest reference {}",
                record.name, entry.name
            )));
        }
        crates.push(record);
    }
    // Every supplied body must be referenced exactly once by the manifest.
    let unreferenced: Vec<&str> = by_name
        .keys()
        .filter(|name| !consumed.contains(**name))
        .copied()
        .collect();
    if !unreferenced.is_empty() {
        return Err(crate::DiscoveryError::CatalogCorruption(format!(
            "crate bodies not referenced by the manifest: {}",
            unreferenced.join(", ")
        )));
    }

    Ok(StructuralCatalog {
        schema_version: manifest.schema_version,
        version: manifest.version,
        description: manifest.description,
        content_hash: manifest.content_hash,
        probe_descriptors: manifest.probe_descriptors,
        wasm_surface: manifest.wasm_surface,
        dependency_edges: manifest.dependency_edges,
        crates,
    })
}
