// SPDX-License-Identifier: MIT OR Apache-2.0

//! Deterministic workspace catalog generation and drift verification.
//!
//! [`generate_workspace_catalog`] composes every Task-5 structural pass
//! (inventory, modules, exports, signatures, traits, cfg, macros, WASM) into a
//! single [`StructuralCatalog`]. The function is pure, read-only, and
//! performs no Cargo/rustc/network access. [`verify_checked_in`] compares the
//! canonical generated bytes to a fixed checked-in file and returns typed drift
//! or corruption errors.

use std::{collections::BTreeSet, fs, path::Path};

use sha2::{Digest, Sha256};

use crate::{DiscoveryError, DiscoveryResult};

use super::{
    cfg::{cfg_gates, CfgStatus, CfgSurfaceKind},
    exports::export_graph,
    inventory::{inventory_workspace, TargetKind},
    macros::macro_catalog,
    modules::module_graph,
    signatures::{signature_catalog, FieldLabel},
    traits::trait_relationships,
    wasm::{default_capability_mappings, WasmSurface},
    CfgGate, MacroKind, SignatureKind,
};

use crate::catalog::model::{
    CfgGateRecord, CrateRecord, DependencyEdgeRecord, DependencyRecord, ExampleRecord,
    FeatureRecord, FieldRecord, ItemRecord, ItemShape, ItemVariantRecord, MacroCatalogRecord,
    RelationshipEndpointRecord, StructuralCatalog, SuperTraitConstraintRecord, TargetRecord,
    TraitDefinitionRecord, TraitImplementationRecord, TraitItemRecord, VariantDataRecord,
    VariantFieldRecord, VariantRecord, WasmCapabilityMappingRef, WasmSurfaceRef,
};

// ============================================================================
// Public API
// ============================================================================

/// Generates a deterministic [`StructuralCatalog`] from a workspace root.
///
/// The function is read-only: it reads Cargo manifests and Rust source files
/// but performs no Cargo, rustc, build-script, or network access. It naturally
/// excludes `target/`, `.git/`, and `.worktrees/` directories because it only
/// reads the files explicitly referenced by workspace manifests and module
/// declarations.
///
/// The `amari-discovery` package, when present, is excluded from the output so
/// the catalog never indexes itself. The WASM surface is loaded from the
/// checked-in `catalog/generated-wasm.json` and probe descriptors from
/// `catalog/probes.toml` — both are required for schema2 generation and
/// produce typed errors when missing or malformed.
///
/// The returned catalog has `content_hash` already populated with a
/// deterministic SHA-256 hash of the canonical pretty JSON (excluding the hash
/// field itself).
///
/// # Errors
///
/// Returns [`DiscoveryError::CatalogCorruption`] when manifests are missing,
/// malformed, or when the required `amari-discovery` package is absent, or
/// when required inputs (`probes.toml`, `generated-wasm.json`) are missing or
/// invalid.
pub fn generate_workspace_catalog(root: &Path) -> DiscoveryResult<StructuralCatalog> {
    let canonical_root = fs::canonicalize(root).map_err(|error| {
        DiscoveryError::CatalogCorruption(format!(
            "cannot resolve workspace root {}: {error}",
            root.display()
        ))
    })?;

    // Ensure amari-discovery exists in the workspace.
    let discovery_manifest = canonical_root.join("amari-discovery/Cargo.toml");
    if !discovery_manifest.is_file() {
        return Err(DiscoveryError::CatalogCorruption(
            "workspace root must contain amari-discovery/Cargo.toml".into(),
        ));
    }

    // -------------------------------------------------------------------
    // 1. Inventory workspace packages.
    // -------------------------------------------------------------------
    let inventory = inventory_workspace(&canonical_root)?;

    // -------------------------------------------------------------------
    // 2. Build cross-crate dependency edges.
    // -------------------------------------------------------------------
    let mut dep_edges: Vec<DependencyEdgeRecord> = Vec::new();
    for pkg in &inventory.packages {
        for dep in &pkg.dependencies {
            if inventory.package(&dep.package).is_some() {
                dep_edges.push(DependencyEdgeRecord {
                    from: pkg.name.clone(),
                    to: dep.package.clone(),
                });
            }
        }
    }
    dep_edges.sort();

    // -------------------------------------------------------------------
    // 3. For each package, run structural passes on its library target.
    // -------------------------------------------------------------------
    let mut crates: Vec<CrateRecord> = Vec::new();

    for pkg in &inventory.packages {
        let crate_name = pkg.name.clone();
        let rust_name = crate_name.replace('-', "_");

        // Workspace-relative directory: use manifest_path parent, not package
        // name. For the root package manifest_path is just "Cargo.toml", parent
        // is "".
        let pkg_dir_rel = Path::new(&pkg.manifest_path)
            .parent()
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_default();

        let pkg_dir = if pkg_dir_rel.is_empty() {
            canonical_root.clone()
        } else {
            canonical_root.join(&pkg_dir_rel)
        };

        // Resolve the library source path.
        let lib_target = pkg.targets.iter().find(|t| t.kind == TargetKind::Library);
        let lib_source_path = lib_target.map(|t| t.path.as_str()).filter(|p| {
            // Only process real library source files (not cdylib stubs without
            // actual API surface). amari-wasm's cdylib is handled via WASM path.
            let full = pkg_dir.join(p);
            full.is_file()
        });

        // Features.
        let features: Vec<FeatureRecord> = pkg
            .features
            .iter()
            .map(|f| FeatureRecord {
                name: f.name.clone(),
                enables: f.enables.clone(),
            })
            .collect();

        // Dependencies.
        let dependencies: Vec<DependencyRecord> = pkg
            .dependencies
            .iter()
            .map(|d| DependencyRecord {
                alias: d.alias.clone(),
                package: d.package.clone(),
                kind: dependency_kind_str(d.kind),
                target: d.target.clone(),
                version: d.version.clone(),
                path: d.path.clone(),
                optional: d.optional,
                default_features: d.default_features,
                features: d.features.clone(),
            })
            .collect();

        // Targets — paths are workspace-relative from manifest parent dir.
        let targets: Vec<TargetRecord> = pkg
            .targets
            .iter()
            .map(|t| TargetRecord {
                name: t.name.clone(),
                kind: target_kind_str(t.kind),
                path: workspace_rel_path(&pkg_dir_rel, &t.path),
                required_features: t.required_features.clone(),
                crate_types: t.crate_types.clone(),
            })
            .collect();

        // Examples — paths are workspace-relative from manifest parent dir.
        let examples: Vec<ExampleRecord> = pkg
            .targets
            .iter()
            .filter(|t| t.kind == TargetKind::Example)
            .map(|t| ExampleRecord {
                name: t.name.clone(),
                path: workspace_rel_path(&pkg_dir_rel, &t.path),
                required_features: t.required_features.clone(),
            })
            .collect();

        // README path when present.
        let readme_file = pkg_dir.join("README.md");
        let readme = if readme_file.is_file() {
            Some(workspace_rel_path(&pkg_dir_rel, "README.md"))
        } else {
            None
        };

        // Module paths (public-only from export graph).
        let mut module_paths: Vec<String> = Vec::new();
        let mut items: Vec<ItemRecord> = Vec::new();
        let mut macros: Vec<MacroCatalogRecord> = Vec::new();
        let mut trait_defs: Vec<TraitDefinitionRecord> = Vec::new();
        let mut trait_impls: Vec<TraitImplementationRecord> = Vec::new();
        let mut cfg_records: Vec<CfgGateRecord> = Vec::new();

        if let Some(source_path) = lib_source_path {
            // --- Module graph (private) ---
            let graph = module_graph(&pkg_dir, source_path).map_err(|error| {
                DiscoveryError::CatalogCorruption(format!(
                    "package {}: cannot build module graph for {}: {error}",
                    crate_name, source_path,
                ))
            })?;

            // --- Export graph (public) ---
            let exports = export_graph(&graph, &pkg_dir).map_err(|error| {
                DiscoveryError::CatalogCorruption(format!(
                    "package {}: cannot build export graph: {error}",
                    crate_name,
                ))
            })?;

            // Public modules: derive from reachable ExportGraph module records
            // (plus the crate root), never raw private ModuleGraph modules.
            let mut seen_modules: BTreeSet<String> = BTreeSet::new();
            // The crate root itself is always a public module path.
            seen_modules.insert(rust_name.to_string());
            for export in &exports.exports {
                if export.path == "crate" {
                    continue; // Already inserted.
                }
                // Module exports represent public module paths.
                if matches!(&export.source, super::exports::ExportSource::Module { .. }) {
                    let public = public_module_path(&crate_name, &export.path);
                    seen_modules.insert(public);
                }
            }
            module_paths = seen_modules.into_iter().collect();
            module_paths.sort();

            // --- Signature catalog ---
            let sigs = signature_catalog(&graph, &exports, &pkg_dir).map_err(|error| {
                DiscoveryError::CatalogCorruption(format!(
                    "package {}: cannot build signature catalog: {error}",
                    crate_name,
                ))
            })?;

            // Group signatures by exported path for canonical items.
            // Each unique public path gets one ItemRecord. When multiple
            // cfg/source variants share the same path, all distinct variants
            // are preserved in `variants`. The canonical summary fields are
            // only populated when a single variant exists (backward compat).
            // Associated items are emitted as top-level ItemRecords only;
            // no owner item carries an inline associated array.
            let mut path_groups: std::collections::BTreeMap<
                String,
                Vec<&super::signatures::SignatureRecord>,
            > = std::collections::BTreeMap::new();
            for sig in &sigs.records {
                let public_path = public_item_path(&crate_name, &sig.path, &sig.source.ident);
                path_groups.entry(public_path).or_default().push(sig);
            }

            for (public_path, sigs) in &path_groups {
                // Collect distinct variants keyed by (source, kind, signature).
                let mut variant_records: Vec<ItemVariantRecord> = Vec::new();
                let mut seen_variants: std::collections::BTreeSet<(
                    &super::signatures::SignatureSource,
                    super::signatures::SignatureKind,
                    &str,
                )> = std::collections::BTreeSet::new();
                for sig in sigs {
                    let key = (&sig.source, sig.kind, sig.signature.as_str());
                    if !seen_variants.insert(key) {
                        continue;
                    }
                    let source_rel = workspace_rel_path(&pkg_dir_rel, &sig.source.source_path);
                    let source_module = public_module_path(&crate_name, &sig.source.module);
                    let is_reexport =
                        sig.path != format!("{}::{}", sig.source.module, sig.source.ident);
                    let shape = convert_shape(&sig.shape);
                    variant_records.push(ItemVariantRecord {
                        kind: signature_kind_str(sig.kind),
                        signature: Some(sig.signature.clone()),
                        shape,
                        source_path: Some(source_rel),
                        source_module: Some(source_module),
                        is_reexport,
                        declaration_module: Some(public_module_path(
                            &crate_name,
                            &sig.source.module,
                        )),
                        declaration_ident: Some(sig.source.ident.clone()),
                    });
                }

                // Deterministic variant sort.
                variant_records.sort_by(|a, b| {
                    a.source_module
                        .cmp(&b.source_module)
                        .then_with(|| a.signature.cmp(&b.signature))
                        .then_with(|| a.kind.cmp(&b.kind))
                });

                // Canonical summary fields populated only for single-variant items.
                let (kind, signature, shape, source_path, is_reexport, source_module) =
                    if variant_records.len() == 1 {
                        let v = &variant_records[0];
                        (
                            Some(v.kind.clone()),
                            v.signature.clone(),
                            v.shape.clone(),
                            v.source_path.clone(),
                            v.is_reexport,
                            v.source_module.clone(),
                        )
                    } else {
                        (None, None, None, None, false, None)
                    };

                items.push(ItemRecord {
                    path: public_path.to_string(),
                    kind,
                    signature,
                    shape,
                    source_path,
                    is_reexport,
                    source_module,
                    variants: variant_records,
                });
            }

            // Emit associated items as top-level ItemRecords so semantic
            // symbol_refs resolve (e.g. `amari_core::Multivector::geometric_product`).
            // Associated items also get variant grouping by source identity.
            {
                let mut assoc_path_groups: std::collections::BTreeMap<
                    String,
                    Vec<(
                        &super::signatures::SignatureRecord,
                        &super::signatures::AssociatedItem,
                    )>,
                > = std::collections::BTreeMap::new();
                for sigs in path_groups.values() {
                    for sig in sigs {
                        for assoc in &sig.associated {
                            let owner_public =
                                public_item_path(&crate_name, &sig.path, &sig.source.ident);
                            let assoc_path = format!("{owner_public}::{name}", name = assoc.name);
                            assoc_path_groups
                                .entry(assoc_path)
                                .or_default()
                                .push((*sig, assoc));
                        }
                    }
                }

                for (assoc_path, assoc_variants) in &assoc_path_groups {
                    let mut variant_records: Vec<ItemVariantRecord> = Vec::new();
                    let mut seen_keys: std::collections::BTreeSet<(
                        &super::signatures::SignatureSource,
                        super::signatures::AssociatedKind,
                        &str,
                    )> = std::collections::BTreeSet::new();
                    for (sig, assoc) in assoc_variants {
                        let key = (&sig.source, assoc.kind, assoc.signature.as_str());
                        if !seen_keys.insert(key) {
                            continue;
                        }
                        let source_rel = workspace_rel_path(&pkg_dir_rel, &sig.source.source_path);
                        let source_module = public_module_path(&crate_name, &sig.source.module);
                        let is_reexport =
                            sig.path != format!("{}::{}", sig.source.module, sig.source.ident);
                        variant_records.push(ItemVariantRecord {
                            kind: associated_kind_str(assoc.kind),
                            signature: Some(assoc.signature.clone()),
                            shape: None,
                            source_path: Some(source_rel),
                            source_module: Some(source_module),
                            is_reexport,
                            declaration_module: Some(public_module_path(
                                &crate_name,
                                &sig.source.module,
                            )),
                            declaration_ident: Some(format!(
                                "{}::{}",
                                sig.source.ident, assoc.name
                            )),
                        });
                    }
                    variant_records.sort_by(|a, b| {
                        a.source_module
                            .cmp(&b.source_module)
                            .then_with(|| a.signature.cmp(&b.signature))
                            .then_with(|| a.kind.cmp(&b.kind))
                    });

                    let (kind, signature, source_path, is_reexport, source_module) =
                        if variant_records.len() == 1 {
                            let v = &variant_records[0];
                            (
                                Some(v.kind.clone()),
                                v.signature.clone(),
                                v.source_path.clone(),
                                v.is_reexport,
                                v.source_module.clone(),
                            )
                        } else {
                            (None, None, None, false, None)
                        };

                    items.push(ItemRecord {
                        path: assoc_path.to_string(),
                        kind,
                        signature,
                        shape: None,
                        source_path,
                        is_reexport,
                        source_module,
                        variants: variant_records,
                    });
                }
            }

            // --- Trait relationships ---
            let traits = trait_relationships(&graph, &exports, &pkg_dir).map_err(|error| {
                DiscoveryError::CatalogCorruption(format!(
                    "package {}: cannot build trait relationships: {error}",
                    crate_name,
                ))
            })?;

            for td in &traits.definitions {
                let export_path = public_item_path(&crate_name, &td.export_path, "");
                let source_rel = workspace_rel_path(&pkg_dir_rel, &td.source_path);
                trait_defs.push(TraitDefinitionRecord {
                    export_path: export_path.trim_end_matches("::").to_string(),
                    source_path: source_rel,
                    source_ordinal: td.source_ordinal,
                    trait_endpoint: convert_endpoint(&td.trait_endpoint, &crate_name),
                    supertraits: td
                        .supertraits
                        .iter()
                        .map(|s| SuperTraitConstraintRecord {
                            endpoint: convert_endpoint(&s.endpoint, &crate_name),
                        })
                        .collect(),
                    required_items: td
                        .required_items
                        .iter()
                        .map(|i| TraitItemRecord {
                            name: i.name.clone(),
                            kind: associated_kind_str(i.kind),
                            signature: i.signature.clone(),
                            status: "required".to_string(),
                        })
                        .collect(),
                    provided_items: td
                        .provided_items
                        .iter()
                        .map(|i| TraitItemRecord {
                            name: i.name.clone(),
                            kind: associated_kind_str(i.kind),
                            signature: i.signature.clone(),
                            status: "provided".to_string(),
                        })
                        .collect(),
                });
            }

            for ti in &traits.implementations {
                let source_rel = workspace_rel_path(&pkg_dir_rel, &ti.source_path);
                // Package-qualify trait_path and impl_type_path for local endpoints.
                let trait_path = qualify_local_path(&ti.trait_path, &crate_name);
                let impl_type_path = qualify_local_path(&ti.impl_type_path, &crate_name);
                trait_impls.push(TraitImplementationRecord {
                    trait_path,
                    impl_type_path,
                    source_path: source_rel,
                    source_ordinal: ti.source_ordinal,
                    trait_endpoint: convert_endpoint(&ti.trait_endpoint, &crate_name),
                    impl_type_endpoint: convert_endpoint(&ti.impl_type_endpoint, &crate_name),
                    generics: ti.generics.clone(),
                    unsafe_trait: ti.unsafe_trait,
                    negative: ti.negative,
                    is_derived: ti.is_derived,
                });
            }

            // --- cfg gates ---
            let gates = cfg_gates(&graph, &exports, &sigs, pkg, &pkg_dir).map_err(|error| {
                DiscoveryError::CatalogCorruption(format!(
                    "package {}: cannot build cfg gates: {error}",
                    crate_name,
                ))
            })?;

            for g in &gates {
                let public_path = public_item_path(&crate_name, &g.path, "");
                let source_rel = workspace_rel_path(&pkg_dir_rel, &g.source_path);
                cfg_records.push(CfgGateRecord {
                    path: public_path.trim_end_matches("::").to_string(),
                    source_path: source_rel,
                    source_ordinal: g.source_ordinal,
                    gate: gate_display(&g.gate),
                    status: cfg_status_str(g.status),
                    surface_kind: cfg_surface_kind_str(g.surface_kind),
                });
            }

            // --- Macro catalog ---
            // Run macro_catalog for EVERY library target, not only proc-macro.
            // inventory itself gates proc attrs. Declarative macros with
            // #[macro_export] are collected regardless of target type.
            let mc = macro_catalog(&graph, &inventory, &crate_name, &pkg_dir).map_err(|error| {
                DiscoveryError::CatalogCorruption(format!(
                    "package {}: cannot build macro catalog: {error}",
                    crate_name,
                ))
            })?;

            for m in &mc.records {
                let public_path = public_item_path(&crate_name, &m.path, &m.name);
                let source_rel = workspace_rel_path(&pkg_dir_rel, &m.source.source_path);
                macros.push(MacroCatalogRecord {
                    path: public_path,
                    name: m.name.clone(),
                    kind: macro_kind_str(m.kind),
                    source_path: source_rel,
                    signature: m.signature.clone(),
                    helpers: m.helpers.clone(),
                });
            }
        }

        // Sort for determinism.
        items.sort_by(|a, b| a.path.cmp(&b.path));
        macros.sort_by(|a, b| a.path.cmp(&b.path));
        trait_defs.sort_by(|a, b| a.export_path.cmp(&b.export_path));
        trait_impls.sort_by(|a, b| {
            a.trait_path
                .cmp(&b.trait_path)
                .then_with(|| a.impl_type_path.cmp(&b.impl_type_path))
        });
        cfg_records.sort_by(|a, b| a.path.cmp(&b.path));
        // Dependencies are already sorted by inventory.
        // Targets are already sorted by inventory.

        crates.push(CrateRecord {
            name: crate_name,
            version: pkg.version.clone(),
            description: pkg.description.clone(),
            license: pkg.license.clone(),
            edition: pkg.edition.clone(),
            manifest_path: pkg.manifest_path.clone(),
            library_outputs: pkg.library_outputs.clone(),
            features,
            dependencies,
            targets,
            items,
            macros,
            trait_definitions: trait_defs,
            trait_implementations: trait_impls,
            cfg_gates: cfg_records,
            examples,
            modules: module_paths,
            readme,
        });
    }

    // -------------------------------------------------------------------
    // 4. WASM surface summary (required for schema2).
    // -------------------------------------------------------------------
    let wasm_surface = read_wasm_surface_summary(&canonical_root)?;

    // -------------------------------------------------------------------
    // 5. Probe descriptors from probes.toml (required for schema2).
    // -------------------------------------------------------------------
    let probes_path = canonical_root.join("amari-discovery/catalog/probes.toml");
    if !probes_path.is_file() {
        return Err(DiscoveryError::CatalogCorruption(
            "required probes.toml not found at amari-discovery/catalog/probes.toml".into(),
        ));
    }
    let toml_str = fs::read_to_string(&probes_path).map_err(|error| {
        DiscoveryError::CatalogCorruption(format!("cannot read probes.toml: {error}"))
    })?;
    let manifest: crate::catalog::ProbeManifest = toml::from_str(&toml_str).map_err(|error| {
        DiscoveryError::CatalogCorruption(format!("invalid probes.toml: {error}"))
    })?;
    let probe_descriptors = manifest.probes;

    // -------------------------------------------------------------------
    // 6. Assemble catalog with content_hash pre-populated.
    // -------------------------------------------------------------------
    let version = inventory.workspace_version.clone();
    let mut catalog = StructuralCatalog {
        schema_version: 2,
        version: version.clone(),
        description: format!(
            "Generated structural catalog for Amari {}: {} crates, {} dependency edges",
            version,
            crates.len(),
            dep_edges.len(),
        ),
        content_hash: None, // Filled below
        crates,
        probe_descriptors,
        wasm_surface,
        dependency_edges: dep_edges,
    };

    // Compute content hash: hash the canonical pretty JSON with content_hash absent.
    let hash = {
        let mut hasher = Sha256::new();
        let json_without_hash = serde_json::to_vec_pretty(&catalog)?;
        hasher.update(&json_without_hash);
        hex::encode(hasher.finalize())
    };
    catalog.content_hash = Some(hash);

    Ok(catalog)
}

/// Verifies that a generated catalog matches a checked-in snapshot file.
///
/// Generates the catalog from `root`, serializes to canonical JSON, and
/// compares with the bytes in `checked_in`. Returns `Ok(())` on exact match
/// or a typed [`DiscoveryError::CatalogCorruption`] describing the drift.
///
/// This function does **not** write any files.
///
/// # Errors
///
/// Returns [`DiscoveryError::CatalogCorruption`] when the generated catalog
/// differs from the checked-in file or when the checked-in file cannot be read.
pub fn verify_checked_in(root: &Path, checked_in: &Path) -> DiscoveryResult<()> {
    let generated = generate_workspace_catalog(root)?;
    let canonical_bytes = canonical_json_bytes(&generated)?;
    let expected_bytes = fs::read(checked_in).map_err(|error| {
        DiscoveryError::CatalogCorruption(format!(
            "cannot read checked-in catalog {}: {error}",
            checked_in.display()
        ))
    })?;

    if canonical_bytes == expected_bytes {
        Ok(())
    } else {
        let gen_len = canonical_bytes.len();
        let exp_len = expected_bytes.len();
        let gen_str = String::from_utf8_lossy(&canonical_bytes);
        let exp_str = String::from_utf8_lossy(&expected_bytes);

        // Find first differing line number and show a safe snippet.
        let gen_lines: Vec<&str> = gen_str.lines().collect();
        let exp_lines: Vec<&str> = exp_str.lines().collect();
        let max_lines = gen_lines.len().max(exp_lines.len());

        let mut first_diff_line = 0usize;
        let mut first_diff_gen = "";
        let mut first_diff_exp = "";
        let mut total_differing = 0usize;

        for i in 0..max_lines {
            let g = gen_lines.get(i).copied().unwrap_or("<EOF>");
            let e = exp_lines.get(i).copied().unwrap_or("<EOF>");
            if g != e {
                total_differing += 1;
                if first_diff_line == 0 {
                    first_diff_line = i + 1; // 1-indexed
                    first_diff_gen = g;
                    first_diff_exp = e;
                }
            }
        }

        Err(DiscoveryError::CatalogCorruption(format!(
            "catalog drift detected: generated {gen_len} bytes, checked-in {exp_len} bytes, \
             {total_differing} differing lines. First difference at line {first_diff_line}: \
             generated={gen_snippet}, expected={exp_snippet}. \
             Run the catalog generation example to regenerate.",
            gen_snippet = first_diff_gen.chars().take(120).collect::<String>(),
            exp_snippet = first_diff_exp.chars().take(120).collect::<String>(),
        )))
    }
}

/// Internal: serializes a catalog to canonical JSON bytes (pretty with trailing newline).
fn canonical_json_bytes(catalog: &StructuralCatalog) -> DiscoveryResult<Vec<u8>> {
    let mut json_bytes = serde_json::to_vec_pretty(catalog)?;
    json_bytes.push(b'\n');
    Ok(json_bytes)
}

// ============================================================================
// Helpers: path conversion, kind mapping
// ============================================================================

/// Converts a package-relative path to a workspace-relative path using the
/// manifest parent directory. For the root package, where manifest parent is
/// empty, paths pass through unchanged (src/lib.rs, examples/foo.rs, README.md).
fn workspace_rel_path(pkg_dir_rel: &str, path: &str) -> String {
    if pkg_dir_rel.is_empty() {
        path.to_string()
    } else {
        format!("{pkg_dir_rel}/{path}")
    }
}

/// Converts `crate::module::Name` to `package_name::module::Name`.
fn public_item_path(crate_name: &str, internal_path: &str, fallback_name: &str) -> String {
    let rust_name = crate_name.replace('-', "_");
    if let Some(rest) = internal_path.strip_prefix("crate::") {
        if rest.is_empty() {
            format!("{rust_name}::{fallback_name}")
        } else {
            format!("{rust_name}::{rest}")
        }
    } else {
        format!("{rust_name}::{internal_path}")
    }
}

/// Converts `crate::module::Name` to `package_name::module::Name` for module paths.
fn public_module_path(crate_name: &str, internal_path: &str) -> String {
    let rust_name = crate_name.replace('-', "_");
    if let Some(rest) = internal_path.strip_prefix("crate") {
        if rest.is_empty() {
            rust_name
        } else if let Some(deeper) = rest.strip_prefix("::") {
            format!("{rust_name}::{deeper}")
        } else {
            format!("{rust_name}{rest}")
        }
    } else {
        format!("{rust_name}::{internal_path}")
    }
}

/// Package-qualifies a local path (one starting with `crate::`) and leaves
/// external paths unchanged.
fn qualify_local_path(path: &str, crate_name: &str) -> String {
    let rust_name = crate_name.replace('-', "_");
    if let Some(rest) = path.strip_prefix("crate::") {
        if rest.is_empty() {
            rust_name
        } else {
            format!("{rust_name}::{rest}")
        }
    } else if path == "crate" {
        rust_name
    } else {
        path.to_string()
    }
}

fn dependency_kind_str(kind: super::inventory::DependencyKind) -> String {
    match kind {
        super::inventory::DependencyKind::Normal => "normal".into(),
        super::inventory::DependencyKind::Build => "build".into(),
        super::inventory::DependencyKind::Development => "development".into(),
    }
}

fn target_kind_str(kind: TargetKind) -> String {
    match kind {
        TargetKind::Library => "library".into(),
        TargetKind::Binary => "binary".into(),
        TargetKind::Example => "example".into(),
    }
}

fn signature_kind_str(kind: SignatureKind) -> String {
    match kind {
        SignatureKind::Function => "fn".into(),
        SignatureKind::Struct => "struct".into(),
        SignatureKind::Enum => "enum".into(),
        SignatureKind::Union => "union".into(),
        SignatureKind::Constant => "const".into(),
        SignatureKind::Static => "static".into(),
        SignatureKind::Trait => "trait".into(),
        SignatureKind::TypeAlias => "type".into(),
    }
}

fn associated_kind_str(kind: super::signatures::AssociatedKind) -> String {
    match kind {
        super::signatures::AssociatedKind::Method => "method".into(),
        super::signatures::AssociatedKind::Const => "const".into(),
        super::signatures::AssociatedKind::Type => "type".into(),
    }
}

fn macro_kind_str(kind: MacroKind) -> String {
    match kind {
        MacroKind::Declarative => "declarative".into(),
        MacroKind::ProcMacro => "proc_macro".into(),
        MacroKind::ProcMacroAttribute => "proc_macro_attribute".into(),
        MacroKind::ProcMacroDerive => "proc_macro_derive".into(),
    }
}

fn cfg_status_str(status: CfgStatus) -> String {
    match status {
        CfgStatus::Enabled => "enabled".into(),
        CfgStatus::Disabled => "disabled".into(),
        CfgStatus::Unknown => "unknown".into(),
    }
}

fn cfg_surface_kind_str(kind: CfgSurfaceKind) -> String {
    match kind {
        CfgSurfaceKind::TopLevel => "top_level".into(),
        CfgSurfaceKind::Module => "module".into(),
        CfgSurfaceKind::InherentMethod => "inherent_method".into(),
        CfgSurfaceKind::InherentConst => "inherent_const".into(),
        CfgSurfaceKind::TraitMethod => "trait_method".into(),
        CfgSurfaceKind::TraitConst => "trait_const".into(),
        CfgSurfaceKind::TraitType => "trait_type".into(),
    }
}

fn gate_display(gate: &CfgGate) -> String {
    match gate {
        CfgGate::Always => "always".into(),
        CfgGate::Known(expr) => expr.to_string(),
        CfgGate::Conditional { expr, unknowns: _ } => {
            format!("conditional({expr})")
        }
        CfgGate::Unknown(unknowns) => {
            format!("unknown({})", unknowns.join(", "))
        }
    }
}

fn convert_shape(shape: &Option<super::signatures::AggregateShape>) -> Option<ItemShape> {
    let shape = shape.as_ref()?;
    match shape {
        super::signatures::AggregateShape::Struct { fields } => Some(ItemShape::Struct {
            fields: fields.iter().map(convert_field).collect(),
        }),
        super::signatures::AggregateShape::Enum { variants } => Some(ItemShape::Enum {
            variants: variants.iter().map(convert_variant).collect(),
        }),
        super::signatures::AggregateShape::Union { fields } => Some(ItemShape::Union {
            fields: fields.iter().map(convert_field).collect(),
        }),
    }
}

fn convert_field(f: &super::signatures::FieldShape) -> FieldRecord {
    let label = match &f.label {
        FieldLabel::Named(n) => n.clone(),
        FieldLabel::Positional(i) => i.to_string(),
    };
    FieldRecord {
        label,
        ty: f.ty.clone(),
    }
}

fn convert_variant(v: &super::signatures::VariantShape) -> VariantRecord {
    let data = match &v.data {
        super::signatures::VariantData::Unit => VariantDataRecord::Unit,
        super::signatures::VariantData::Tuple(types) => VariantDataRecord::Tuple {
            types: types.clone(),
        },
        super::signatures::VariantData::Struct(fields) => VariantDataRecord::Struct {
            fields: fields
                .iter()
                .map(|vf| VariantFieldRecord {
                    name: vf.name.clone(),
                    ty: vf.ty.clone(),
                })
                .collect(),
        },
    };
    VariantRecord {
        name: v.name.clone(),
        data,
    }
}

fn convert_endpoint(
    ep: &super::traits::RelationshipEndpoint,
    crate_name: &str,
) -> RelationshipEndpointRecord {
    match ep {
        super::traits::RelationshipEndpoint::Local { module, ident } => {
            let qualified_module = public_module_path(crate_name, module);
            RelationshipEndpointRecord::Local {
                module: qualified_module,
                ident: ident.clone(),
            }
        }
        super::traits::RelationshipEndpoint::External { path } => {
            RelationshipEndpointRecord::External { path: path.clone() }
        }
    }
}

/// Reads the checked-in `generated-wasm.json` and returns a summary reference.
///
/// Schema2 requires that the stored `capability_mappings` exactly equal the
/// recomputed default mappings — mismatches produce a typed
/// [`DiscoveryError::CatalogCorruption`] so that the 5C3 artifact stays
/// authoritative and silent mapping loss is impossible.
fn read_wasm_surface_summary(root: &Path) -> DiscoveryResult<Option<WasmSurfaceRef>> {
    let wasm_path = root.join("amari-discovery/catalog/generated-wasm.json");
    if !wasm_path.is_file() {
        return Err(DiscoveryError::CatalogCorruption(
            "required generated-wasm.json not found at amari-discovery/catalog/generated-wasm.json"
                .into(),
        ));
    }
    let json_str = fs::read_to_string(&wasm_path).map_err(|error| {
        DiscoveryError::CatalogCorruption(format!("cannot read generated-wasm.json: {error}"))
    })?;
    let surface: WasmSurface = serde_json::from_str(&json_str).map_err(|error| {
        DiscoveryError::CatalogCorruption(format!("invalid generated-wasm.json: {error}"))
    })?;

    // Recompute default mappings — propagate errors, never fall back to empty.
    let recomputed = default_capability_mappings(&surface).map_err(|error| {
        DiscoveryError::CatalogCorruption(format!(
            "cannot compute default capability mappings: {error}"
        ))
    })?;

    // The checked-in artifact is authoritative: stored mappings must exactly
    // equal recomputed defaults. Mismatch is typed CatalogCorruption.
    if surface.capability_mappings != recomputed {
        return Err(DiscoveryError::CatalogCorruption(format!(
            "capability_mappings in generated-wasm.json ({stored}) do not match \
             recomputed defaults ({recomputed}); regenerate generated-wasm.json",
            stored = surface.capability_mappings.len(),
            recomputed = recomputed.len(),
        )));
    }

    let capability_mappings: Vec<WasmCapabilityMappingRef> = surface
        .capability_mappings
        .into_iter()
        .map(|m| WasmCapabilityMappingRef {
            wasm_path: m.wasm_path,
            capability_id: m.capability_id.to_string(),
        })
        .collect();

    Ok(Some(WasmSurfaceRef {
        path: "amari-discovery/catalog/generated-wasm.json".into(),
        source_hash: surface.source_hash,
        class_count: surface.classes.len(),
        function_count: surface.functions.len(),
        enum_count: surface.enums.len(),
        interface_count: surface.interfaces.len(),
        type_alias_count: surface.type_aliases.len(),
        capability_mappings,
    }))
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn public_item_path_converts_crate_prefix() {
        assert_eq!(
            public_item_path(
                "amari-core",
                "crate::algebra::ga::Multivector",
                "Multivector"
            ),
            "amari_core::algebra::ga::Multivector"
        );
        assert_eq!(
            public_item_path("amari-core", "crate::Rotor", "Rotor"),
            "amari_core::Rotor"
        );
        assert_eq!(
            public_item_path("amari-core", "crate::Multivector", ""),
            "amari_core::Multivector"
        );
    }

    #[test]
    fn public_module_path_converts_crate_root() {
        assert_eq!(public_module_path("amari-core", "crate"), "amari_core");
        assert_eq!(
            public_module_path("amari-core", "crate::algebra::ga"),
            "amari_core::algebra::ga"
        );
    }

    #[test]
    fn workspace_rel_path_root_package_passes_through() {
        assert_eq!(workspace_rel_path("", "src/lib.rs"), "src/lib.rs");
        assert_eq!(
            workspace_rel_path("", "examples/basic.rs"),
            "examples/basic.rs"
        );
        assert_eq!(workspace_rel_path("", "README.md"), "README.md");
    }

    #[test]
    fn workspace_rel_path_sub_package_prepends_dir() {
        assert_eq!(
            workspace_rel_path("amari-core", "src/lib.rs"),
            "amari-core/src/lib.rs"
        );
        assert_eq!(
            workspace_rel_path("amari-discovery", "catalog/generated.json"),
            "amari-discovery/catalog/generated.json"
        );
    }

    #[test]
    fn qualify_local_path_converts_crate_to_rust_name() {
        assert_eq!(
            qualify_local_path("crate::MyTrait", "amari-core"),
            "amari_core::MyTrait"
        );
        assert_eq!(
            qualify_local_path("crate::algebra::ga::Multivector", "amari-core"),
            "amari_core::algebra::ga::Multivector"
        );
        assert_eq!(qualify_local_path("Default", "amari-core"), "Default"); // External
    }
}
