// SPDX-License-Identifier: MIT OR Apache-2.0
//! Generates the per-crate split catalog under `catalog/` (CORE-CAT1).
//!
//! Usage: cargo run -p amari-discovery --example generate_catalog <workspace-root>
//!
//! Writes, under `<root>/amari-discovery/catalog/`:
//! - `manifest.json` — non-crate fields, aggregate hash, crate file refs;
//! - `crates/<crate>.json` — one canonical file per crate;
//! - `index.rs` — generated compile-time include table for the loader.
//!
//! Removes the legacy monolithic `generated.json` and any stale per-crate
//! files. Output is deterministic: running twice produces an identical tree.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process;

use amari_discovery::{generate_workspace_catalog, split_catalog};

fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let tmp_path = path.with_extension(
        path.extension()
            .map(|e| e.to_string_lossy().into_owned() + ".tmp")
            .unwrap_or_else(|| "tmp".into()),
    );
    let write_result = (|| -> Result<(), String> {
        let mut file = fs::File::create(&tmp_path)
            .map_err(|e| format!("Error creating temp file {}: {e}", tmp_path.display()))?;
        file.write_all(bytes)
            .map_err(|e| format!("Error writing temp file {}: {e}", tmp_path.display()))?;
        file.sync_all()
            .map_err(|e| format!("Error syncing temp file {}: {e}", tmp_path.display()))?;
        drop(file);
        fs::rename(&tmp_path, path).map_err(|e| {
            format!(
                "Error renaming {} to {}: {e}",
                tmp_path.display(),
                path.display()
            )
        })?;
        Ok(())
    })();
    if write_result.is_err() {
        let _ = fs::remove_file(&tmp_path);
    }
    write_result
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() != 2 {
        eprintln!("Usage: {} <workspace-root>", args[0]);
        process::exit(1);
    }

    let root = Path::new(&args[1]);

    let catalog = generate_workspace_catalog(root).unwrap_or_else(|error| {
        eprintln!("Error generating catalog: {error}");
        process::exit(1);
    });

    let output_dir = root.join("amari-discovery/catalog");
    if !output_dir.is_dir() {
        eprintln!(
            "Error: output directory {} must already exist",
            output_dir.display()
        );
        process::exit(1);
    }
    let crates_dir = output_dir.join("crates");
    if let Err(error) = fs::create_dir_all(&crates_dir) {
        eprintln!("Error creating {}: {error}", crates_dir.display());
        process::exit(1);
    }

    let (manifest, bodies) = split_catalog(&catalog).unwrap_or_else(|error| {
        eprintln!("Error splitting catalog: {error}");
        process::exit(1);
    });

    // manifest.json
    let manifest_bytes = {
        let mut bytes = serde_json::to_vec_pretty(&manifest).unwrap_or_else(|error| {
            eprintln!("Error serializing manifest: {error}");
            process::exit(1);
        });
        bytes.push(b'\n');
        bytes
    };
    if let Err(msg) = atomic_write(&output_dir.join("manifest.json"), &manifest_bytes) {
        eprintln!("{msg}");
        process::exit(1);
    }

    // crates/<name>.json
    for (name, body) in &bodies {
        if let Err(msg) = atomic_write(&crates_dir.join(format!("{name}.json")), body.as_bytes()) {
            eprintln!("{msg}");
            process::exit(1);
        }
    }

    // Remove stale per-crate files (renamed/removed crates).
    let expected: std::collections::HashSet<String> = manifest
        .crates
        .iter()
        .map(|e| format!("{}.json", e.name))
        .collect();
    let stale: Vec<_> = fs::read_dir(&crates_dir)
        .unwrap_or_else(|error| {
            eprintln!("Error listing {}: {error}", crates_dir.display());
            process::exit(1);
        })
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry.file_name().to_string_lossy().ends_with(".json")
                && !expected.contains(entry.file_name().to_string_lossy().as_ref())
        })
        .map(|entry| entry.path())
        .collect();
    for path in stale {
        if let Err(error) = fs::remove_file(&path) {
            eprintln!("Error removing stale {}: {error}", path.display());
            process::exit(1);
        }
    }

    // index.rs — generated include table for the compile-time loader.
    let mut index = String::from(
        "// @generated by amari-discovery catalog generator — do not edit.\n\n/// Embedded catalog manifest (split layout).\npub static MANIFEST_JSON: &str = include_str!(\"manifest.json\");\n\n/// Embedded per-crate JSON bodies in manifest order.\npub static CRATE_JSON: &[(&str, &str)] = &[\n",
    );
    for entry in &manifest.crates {
        index.push_str(&format!(
            "    (\"{}\", include_str!(\"crates/{}.json\")),\n",
            entry.name, entry.name
        ));
    }
    index.push_str("];\n");
    if let Err(msg) = atomic_write(&output_dir.join("index.rs"), index.as_bytes()) {
        eprintln!("{msg}");
        process::exit(1);
    }

    // Remove the legacy monolith.
    let monolith = output_dir.join("generated.json");
    if monolith.exists() {
        if let Err(error) = fs::remove_file(&monolith) {
            eprintln!("Error removing legacy {}: {error}", monolith.display());
            process::exit(1);
        }
    }

    let item_count = manifest.totals.items;
    let edge_count = manifest.totals.dependency_edges;
    let hash = manifest.content_hash.as_deref().unwrap_or("none");
    eprintln!(
        "Generated split catalog: {crate_count} crates, {item_count} items, {edge_count} dependency edges, hash {hash} ({crate_count} crate files + manifest.json + index.rs)",
        crate_count = manifest.totals.crates
    );
}
