//! Build script that generates match-table dispatch arms for all
//! (p, q, r) signatures with DIM = p + q + r ≤ MAX_MATCH_DIM.
//!
//! Generates one dispatch function per operation so that
//! `WasmGenericMultivector` methods call the correct const-generic
//! `Multivector<P, Q, R>` monomorphization without boxing or closures.

use std::env;
use std::fs;
use std::path::PathBuf;

const MAX_MATCH_DIM: usize = 6;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest_path = out_dir.join("match_table.rs");

    let mut arms = String::new();
    let mut count = 0usize;
    let mut sigs = Vec::new();

    for dim in 0..=MAX_MATCH_DIM {
        for p in 0..=dim {
            for q in 0..=(dim - p) {
                let r = dim - p - q;
                sigs.push((p, q, r));
                count += 1;
            }
        }
    }

    // Generate the match arms once
    for &(p, q, r) in &sigs {
        arms.push_str(&format!(
            "            ({p}, {q}, {r}) => {{\n",
            p = p,
            q = q,
            r = r,
        ));
        arms.push_str(&format!(
            "                let mv_a = amari_core::Multivector::<{p}, {q}, {r}>::from_coefficients(a.to_vec());\n",
            p = p, q = q, r = r,
        ));
        arms.push_str(&format!(
            "                let mv_b = amari_core::Multivector::<{p}, {q}, {r}>::from_coefficients(b.to_vec());\n",
            p = p, q = q, r = r,
        ));
        arms.push_str("                let mv_c = mv_a.__OP__(&mv_b);\n");
        arms.push_str(
            "                for (i, r) in result.iter_mut().enumerate() { *r = mv_c.get(i); }\n",
        );
        arms.push_str("            }\n");
    }

    let code = format!(
        r#"// Auto-generated by build.rs — DO NOT EDIT
// All (p, q, r) signatures where p+q+r ≤ {max_dim} ({count} combinations)
// Each dispatch_* function matches (p,q,r) and calls the correct
// const-generic Multivector<P,Q,R> monomorphization.

// ---- geometric_product ----

#[inline]
pub(crate) fn dispatch_geometric_product(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
    b: &[f64],
    result: &mut [f64],
) {{
    match (p, q, r) {{
{arms_geo}        _ => unreachable!("signature not in match table"),
    }}
}}

// ---- inner_product ----

#[inline]
pub(crate) fn dispatch_inner_product(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
    b: &[f64],
    result: &mut [f64],
) {{
    match (p, q, r) {{
{arms_inner}        _ => unreachable!("signature not in match table"),
    }}
}}

// ---- outer_product ----

#[inline]
pub(crate) fn dispatch_outer_product(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
    b: &[f64],
    result: &mut [f64],
) {{
    match (p, q, r) {{
{arms_outer}        _ => unreachable!("signature not in match table"),
    }}
}}

// ---- scalar_product ----

#[inline]
pub(crate) fn dispatch_scalar_product(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
    b: &[f64],
) -> f64 {{
    match (p, q, r) {{
{arms_scalar}        _ => unreachable!("signature not in match table"),
    }}
}}

// ---- magnitude ----

#[inline]
pub(crate) fn dispatch_magnitude(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
) -> f64 {{
    match (p, q, r) {{
{arms_mag}        _ => unreachable!("signature not in match table"),
    }}
}}

// ---- exp ----

#[inline]
pub(crate) fn dispatch_exp(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
    result: &mut [f64],
) {{
    match (p, q, r) {{
{arms_exp}        _ => unreachable!("signature not in match table"),
    }}
}}

// ---- normalize ----

/// Returns `true` if normalization succeeded.
#[inline]
pub(crate) fn dispatch_normalize(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
    result: &mut [f64],
) -> bool {{
    match (p, q, r) {{
{arms_norm}        _ => unreachable!("signature not in match table"),
    }}
}}

// ---- inverse ----

/// Returns `true` if the multivector is invertible.
#[inline]
pub(crate) fn dispatch_inverse(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
    result: &mut [f64],
) -> bool {{
    match (p, q, r) {{
{arms_inv}        _ => unreachable!("signature not in match table"),
    }}
}}
"#,
        max_dim = MAX_MATCH_DIM,
        count = count,
        arms_geo = arms.replace("__OP__", "geometric_product"),
        arms_inner = arms.replace("__OP__", "inner_product"),
        arms_outer = arms.replace("__OP__", "outer_product"),
        arms_scalar = generate_scalar_arms(&sigs),
        arms_mag = generate_unary_f64_arms(&sigs, "magnitude"),
        arms_exp = generate_unary_arms(&sigs, "exp"),
        arms_norm = generate_unary_option_arms(&sigs, "normalize"),
        arms_inv = generate_unary_option_arms(&sigs, "inverse"),
    );

    fs::write(&dest_path, code).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
}

fn generate_scalar_arms(sigs: &[(usize, usize, usize)]) -> String {
    let mut arms = String::new();
    for &(p, q, r) in sigs {
        arms.push_str(&format!(
            "            ({p}, {q}, {r}) => {{\n\
                      let mv_a = amari_core::Multivector::<{p}, {q}, {r}>::from_coefficients(a.to_vec());\n\
                      let mv_b = amari_core::Multivector::<{p}, {q}, {r}>::from_coefficients(b.to_vec());\n\
                      mv_a.scalar_product(&mv_b)\n\
             }}\n",
            p = p, q = q, r = r,
        ));
    }
    arms
}

fn generate_unary_f64_arms(sigs: &[(usize, usize, usize)], method: &str) -> String {
    let mut arms = String::new();
    for &(p, q, r) in sigs {
        arms.push_str(&format!(
            "            ({p}, {q}, {r}) => {{\n\
                      let mv = amari_core::Multivector::<{p}, {q}, {r}>::from_coefficients(a.to_vec());\n\
                      mv.{method}()\n\
             }}\n",
            p = p, q = q, r = r, method = method,
        ));
    }
    arms
}

fn generate_unary_arms(sigs: &[(usize, usize, usize)], method: &str) -> String {
    let mut arms = String::new();
    for &(p, q, r) in sigs {
        arms.push_str(&format!(
            "            ({p}, {q}, {r}) => {{\n\
                      let mv = amari_core::Multivector::<{p}, {q}, {r}>::from_coefficients(a.to_vec());\n\
                      let mv_r = mv.{method}();\n\
                      for (i, r) in result.iter_mut().enumerate() {{ *r = mv_r.get(i); }}\n\
             }}\n",
            p = p, q = q, r = r, method = method,
        ));
    }
    arms
}

fn generate_unary_option_arms(sigs: &[(usize, usize, usize)], method: &str) -> String {
    let mut arms = String::new();
    for &(p, q, r) in sigs {
        arms.push_str(&format!(
            "            ({p}, {q}, {r}) => {{\n\
                      let mv = amari_core::Multivector::<{p}, {q}, {r}>::from_coefficients(a.to_vec());\n\
                      if let Some(mv_r) = mv.{method}() {{\n\
                          for (i, r) in result.iter_mut().enumerate() {{ *r = mv_r.get(i); }}\n\
                          true\n\
                      }} else {{\n\
                          false\n\
                      }}\n\
             }}\n",
            p = p, q = q, r = r, method = method,
        ));
    }
    arms
}
