//! Build script that generates the match-table dispatch arms for all
//! (p, q, r) signatures with DIM = p + q + r ≤ MAX_MATCH_DIM.
//!
//! The generated file is included by `amari-wasm/src/generic.rs` at
//! compile time and provides a single `dispatch_generic_product`
//! function that matches a runtime (p, q, r) triple to the correct
//! const-generic `Multivector<P, Q, R>` monomorphization.

use std::env;
use std::fs;
use std::path::PathBuf;

const MAX_MATCH_DIM: usize = 6;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest_path = out_dir.join("match_table.rs");

    let mut arms = String::new();
    let mut count = 0usize;

    for dim in 0..=MAX_MATCH_DIM {
        for p in 0..=dim {
            for q in 0..=(dim - p) {
                let r = dim - p - q;
                arms.push_str(&format!(
                    "            ({p}, {q}, {r}) => generic_product_impl::<{p}, {q}, {r}>(a, b, result),\n",
                    p = p,
                    q = q,
                    r = r,
                ));
                count += 1;
            }
        }
    }

    let code = format!(
        r#"// Auto-generated by build.rs — DO NOT EDIT
// All (p, q, r) signatures where p+q+r ≤ {max_dim} ({count} combinations)

/// Dispatch to the correct Multivector<P, Q, R> monomorphization for a
/// given runtime signature (p, q, r).
///
/// `a` and `b` are coefficient slices of length 2^(p+q+r).
/// `result` is a mutable slice of the same length to write into.
#[inline]
pub(crate) fn dispatch_generic_product(
    p: usize,
    q: usize,
    r: usize,
    a: &[f64],
    b: &[f64],
    result: &mut [f64],
) {{
    match (p, q, r) {{
{arms}        _ => unreachable!("signature not in match table — should have been caught by caller"),
    }}
}}

/// Helper: construct Multivector<P,Q,R>, compute geometric product,
/// extract coefficients.
#[inline]
fn generic_product_impl<const P: usize, const Q: usize, const R: usize>(
    a: &[f64],
    b: &[f64],
    result: &mut [f64],
) {{
    let mv_a = amari_core::Multivector::<P, Q, R>::from_coefficients(a.to_vec());
    let mv_b = amari_core::Multivector::<P, Q, R>::from_coefficients(b.to_vec());
    let mv_c = mv_a.geometric_product(&mv_b);
    let basis_count = amari_core::Multivector::<P, Q, R>::BASIS_COUNT;
    for i in 0..basis_count {{
        result[i] = mv_c.get(i);
    }}
}}
"#,
        max_dim = MAX_MATCH_DIM,
        count = count,
        arms = arms,
    );

    fs::write(&dest_path, code).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
}
