//! Generic (runtime-signature) WASM multivector and rotor types.
//!
//! `WasmGenericMultivector` is the single WASM-bindgen type for all Clifford
//! algebra signatures.  It stores coefficients as a flat `Vec<f64>` plus the
//! metric signature `(p, q, r)`, and dispatches operations through either:
//!
//! * A compile-time match table (DIM ≤ 6, generated by `build.rs`)
//! * A runtime Cayley-table path (DIM > 6)

use amari_core::generic as core_generic;
use wasm_bindgen::prelude::*;

use std::cell::RefCell;
use std::collections::HashMap;

// Include the build-script-generated dispatch functions.
include!(concat!(env!("OUT_DIR"), "/match_table.rs"));

/// Maximum dimension covered by the compile-time match table.
const MAX_MATCH_DIM: usize = 6;

// ========================================================================
// Cayley-table cache for signatures beyond the match table (DIM > 6).
// ========================================================================

struct CayleyTable {
    data: Vec<(usize, f64)>,
    basis_count: usize,
}

impl CayleyTable {
    fn new(p: usize, q: usize, r: usize) -> Self {
        let dim = p + q + r;
        let basis_count = 1 << dim;
        let mut data = Vec::with_capacity(basis_count * basis_count);

        for i in 0..basis_count {
            for j in 0..basis_count {
                let (k, sign) = core_generic::blade_product(p, q, r, dim, i, j);
                data.push((k, sign));
            }
        }

        Self { data, basis_count }
    }

    fn geometric_product(&self, a: &[f64], b: &[f64]) -> Vec<f64> {
        let n = self.basis_count;
        let mut result = vec![0.0; n];

        for (i, &ai) in a.iter().enumerate() {
            if ai == 0.0 {
                continue;
            }
            for (j, &bj) in b.iter().enumerate() {
                if bj == 0.0 {
                    continue;
                }
                let (k, sign) = self.data[i * n + j];
                if sign != 0.0 {
                    result[k] += sign * ai * bj;
                }
            }
        }

        result
    }
}

thread_local! {
    static CAYLEY_CACHE: RefCell<HashMap<(usize, usize, usize), CayleyTable>> =
        RefCell::new(HashMap::new());
}

/// Compute geometric product via cached Cayley table.
fn cayley_geometric_product(p: usize, q: usize, r: usize, a: &[f64], b: &[f64]) -> Vec<f64> {
    CAYLEY_CACHE.with(|cache| {
        let mut cache = cache.borrow_mut();
        let table = cache
            .entry((p, q, r))
            .or_insert_with(|| CayleyTable::new(p, q, r));
        table.geometric_product(a, b)
    })
}

/// Compute inner product via the Cayley table.
fn cayley_inner_product(p: usize, q: usize, r: usize, a: &[f64], b: &[f64]) -> Vec<f64> {
    let dim = p + q + r;
    let n = 1 << dim;
    let mut result = vec![0.0; n];

    // Inner product: keep only terms where |grade(a) - grade(b)| = grade(result)
    for (i, &ai) in a.iter().enumerate() {
        if ai == 0.0 {
            continue;
        }
        let gi = i.count_ones() as isize;
        for (j, &bj) in b.iter().enumerate() {
            if bj == 0.0 {
                continue;
            }
            let gj = j.count_ones() as isize;
            let k = i ^ j;
            let target_grade = (gi - gj).unsigned_abs();
            if k.count_ones() as usize != target_grade {
                continue;
            }
            let (_, sign) = core_generic::blade_product(p, q, r, dim, i, j);
            if sign != 0.0 {
                result[k] += sign * ai * bj;
            }
        }
    }
    result
}

/// Compute outer product via the Cayley table.
fn cayley_outer_product(p: usize, q: usize, r: usize, a: &[f64], b: &[f64]) -> Vec<f64> {
    let dim = p + q + r;
    let n = 1 << dim;
    let mut result = vec![0.0; n];
    for (i, &ai) in a.iter().enumerate() {
        if ai == 0.0 {
            continue;
        }
        let gi = i.count_ones() as usize;
        for (j, &bj) in b.iter().enumerate() {
            if bj == 0.0 {
                continue;
            }
            if (i & j) != 0 {
                continue; // shared basis vectors → would contract
            }
            let gj = j.count_ones() as usize;
            let k = i ^ j;
            if k.count_ones() as usize != gi + gj {
                continue;
            }
            let (_, sign) = core_generic::blade_product(p, q, r, dim, i, j);
            if sign != 0.0 {
                result[k] += sign * ai * bj;
            }
        }
    }
    result
}

// ========================================================================
// Helper: is this signature covered by the match table?
// ========================================================================

fn is_match_table(p: usize, q: usize, r: usize) -> bool {
    p + q + r <= MAX_MATCH_DIM
}

// ========================================================================
// WasmGenericMultivector
// ========================================================================

#[wasm_bindgen]
pub struct WasmGenericMultivector {
    coefficients: Vec<f64>,
    p: usize,
    q: usize,
    r: usize,
}

impl Default for WasmGenericMultivector {
    fn default() -> Self {
        Self::new(3, 0, 0)
    }
}

impl WasmGenericMultivector {
    fn check_same_signature(&self, other: &WasmGenericMultivector) -> Result<(), JsValue> {
        if self.p != other.p || self.q != other.q || self.r != other.r {
            return Err(JsValue::from_str(&format!(
                "Signature mismatch: Cl({},{},{}) vs Cl({},{},{})",
                self.p, self.q, self.r, other.p, other.q, other.r
            )));
        }
        Ok(())
    }

    fn make_result(&self, coeffs: Vec<f64>) -> WasmGenericMultivector {
        WasmGenericMultivector {
            coefficients: coeffs,
            p: self.p,
            q: self.q,
            r: self.r,
        }
    }
}

#[wasm_bindgen]
impl WasmGenericMultivector {
    /// Create a new zero multivector in Cl(p, q, r).
    #[wasm_bindgen(constructor)]
    pub fn new(p: usize, q: usize, r: usize) -> Self {
        let basis_count = 1 << (p + q + r);
        Self {
            coefficients: vec![0.0; basis_count],
            p,
            q,
            r,
        }
    }

    // ---- accessors ----

    #[wasm_bindgen(getter)]
    pub fn p(&self) -> usize {
        self.p
    }
    #[wasm_bindgen(getter)]
    pub fn q(&self) -> usize {
        self.q
    }
    #[wasm_bindgen(getter)]
    pub fn r(&self) -> usize {
        self.r
    }

    #[wasm_bindgen(getter = dim)]
    pub fn dim(&self) -> usize {
        self.p + self.q + self.r
    }

    #[wasm_bindgen(getter = basisCount)]
    pub fn basis_count(&self) -> usize {
        1 << (self.p + self.q + self.r)
    }

    // ---- constructors ----

    #[wasm_bindgen(js_name = fromCoefficients)]
    pub fn from_coefficients(
        p: usize,
        q: usize,
        r: usize,
        coefficients: &[f64],
    ) -> Result<WasmGenericMultivector, JsValue> {
        let expected = 1 << (p + q + r);
        if coefficients.len() != expected {
            return Err(JsValue::from_str(&format!(
                "Cl({},{},{}) requires exactly {} coefficients, got {}",
                p,
                q,
                r,
                expected,
                coefficients.len()
            )));
        }
        Ok(Self {
            coefficients: coefficients.to_vec(),
            p,
            q,
            r,
        })
    }

    #[wasm_bindgen(js_name = scalar)]
    pub fn scalar(p: usize, q: usize, r: usize, value: f64) -> Self {
        let mut mv = Self::new(p, q, r);
        mv.coefficients[0] = value;
        mv
    }

    #[wasm_bindgen(js_name = basisVector)]
    pub fn basis_vector(p: usize, q: usize, r: usize, index: usize) -> Result<Self, JsValue> {
        let dim = p + q + r;
        if index >= dim {
            return Err(JsValue::from_str(&format!(
                "Basis vector index {} out of range for Cl({},{},{}) (dim {})",
                index, p, q, r, dim
            )));
        }
        let mut mv = Self::new(p, q, r);
        mv.coefficients[1 << index] = 1.0;
        Ok(mv)
    }

    // ---- coefficient access ----

    #[wasm_bindgen(js_name = getCoefficients)]
    pub fn get_coefficients(&self) -> Vec<f64> {
        self.coefficients.clone()
    }

    #[wasm_bindgen(js_name = getCoefficient)]
    pub fn get_coefficient(&self, index: usize) -> f64 {
        self.coefficients.get(index).copied().unwrap_or(0.0)
    }

    #[wasm_bindgen(js_name = setCoefficient)]
    pub fn set_coefficient(&mut self, index: usize, value: f64) {
        if index < self.coefficients.len() {
            self.coefficients[index] = value;
        }
    }

    // ---- binary operations ----

    #[wasm_bindgen(js_name = geometricProduct)]
    pub fn geometric_product(
        &self,
        other: &WasmGenericMultivector,
    ) -> Result<WasmGenericMultivector, JsValue> {
        self.check_same_signature(other)?;
        let n = self.coefficients.len();
        let mut result = vec![0.0; n];

        if is_match_table(self.p, self.q, self.r) {
            dispatch_geometric_product(
                self.p,
                self.q,
                self.r,
                &self.coefficients,
                &other.coefficients,
                &mut result,
            );
        } else {
            result = cayley_geometric_product(
                self.p,
                self.q,
                self.r,
                &self.coefficients,
                &other.coefficients,
            );
        }

        Ok(self.make_result(result))
    }

    #[wasm_bindgen(js_name = innerProduct)]
    pub fn inner_product(
        &self,
        other: &WasmGenericMultivector,
    ) -> Result<WasmGenericMultivector, JsValue> {
        self.check_same_signature(other)?;
        let n = self.coefficients.len();
        let mut result = vec![0.0; n];

        if is_match_table(self.p, self.q, self.r) {
            dispatch_inner_product(
                self.p,
                self.q,
                self.r,
                &self.coefficients,
                &other.coefficients,
                &mut result,
            );
        } else {
            result = cayley_inner_product(
                self.p,
                self.q,
                self.r,
                &self.coefficients,
                &other.coefficients,
            );
        }

        Ok(self.make_result(result))
    }

    #[wasm_bindgen(js_name = outerProduct)]
    pub fn outer_product(
        &self,
        other: &WasmGenericMultivector,
    ) -> Result<WasmGenericMultivector, JsValue> {
        self.check_same_signature(other)?;
        let n = self.coefficients.len();
        let mut result = vec![0.0; n];

        if is_match_table(self.p, self.q, self.r) {
            dispatch_outer_product(
                self.p,
                self.q,
                self.r,
                &self.coefficients,
                &other.coefficients,
                &mut result,
            );
        } else {
            result = cayley_outer_product(
                self.p,
                self.q,
                self.r,
                &self.coefficients,
                &other.coefficients,
            );
        }

        Ok(self.make_result(result))
    }

    #[wasm_bindgen(js_name = scalarProduct)]
    pub fn scalar_product(&self, other: &WasmGenericMultivector) -> Result<f64, JsValue> {
        self.check_same_signature(other)?;
        if is_match_table(self.p, self.q, self.r) {
            Ok(dispatch_scalar_product(
                self.p,
                self.q,
                self.r,
                &self.coefficients,
                &other.coefficients,
            ))
        } else {
            let gp = cayley_geometric_product(
                self.p,
                self.q,
                self.r,
                &self.coefficients,
                &other.coefficients,
            );
            Ok(gp[0])
        }
    }

    // ---- unary operations ----

    pub fn reverse(&self) -> WasmGenericMultivector {
        let mut reversed = self.coefficients.clone();
        for (i, c) in reversed.iter_mut().enumerate().skip(1) {
            let grade = i.count_ones() as usize;
            if (grade * (grade.wrapping_sub(1)) / 2) % 2 == 1 {
                *c = -*c;
            }
        }
        self.make_result(reversed)
    }

    #[wasm_bindgen(js_name = gradeProjection)]
    pub fn grade_projection(&self, grade: usize) -> WasmGenericMultivector {
        let mut coeffs = self.coefficients.clone();
        for (i, c) in coeffs.iter_mut().enumerate() {
            if i.count_ones() as usize != grade {
                *c = 0.0;
            }
        }
        self.make_result(coeffs)
    }

    pub fn exp(&self) -> Result<WasmGenericMultivector, JsValue> {
        if !is_match_table(self.p, self.q, self.r) {
            return Err(JsValue::from_str(
                "exp is only supported for DIM ≤ 6 in WASM",
            ));
        }
        let n = self.coefficients.len();
        let mut result = vec![0.0; n];
        dispatch_exp(self.p, self.q, self.r, &self.coefficients, &mut result);
        Ok(self.make_result(result))
    }

    pub fn magnitude(&self) -> Result<f64, JsValue> {
        if !is_match_table(self.p, self.q, self.r) {
            return Err(JsValue::from_str(
                "magnitude is only supported for DIM ≤ 6 in WASM",
            ));
        }
        Ok(dispatch_magnitude(
            self.p,
            self.q,
            self.r,
            &self.coefficients,
        ))
    }

    pub fn norm(&self) -> Result<f64, JsValue> {
        self.magnitude()
    }

    pub fn normalize(&self) -> Result<WasmGenericMultivector, JsValue> {
        if !is_match_table(self.p, self.q, self.r) {
            return Err(JsValue::from_str(
                "normalize is only supported for DIM ≤ 6 in WASM",
            ));
        }
        let n = self.coefficients.len();
        let mut result = vec![0.0; n];
        if dispatch_normalize(self.p, self.q, self.r, &self.coefficients, &mut result) {
            Ok(self.make_result(result))
        } else {
            Err(JsValue::from_str("Cannot normalize zero multivector"))
        }
    }

    pub fn inverse(&self) -> Result<WasmGenericMultivector, JsValue> {
        if !is_match_table(self.p, self.q, self.r) {
            return Err(JsValue::from_str(
                "inverse is only supported for DIM ≤ 6 in WASM",
            ));
        }
        let n = self.coefficients.len();
        let mut result = vec![0.0; n];
        if dispatch_inverse(self.p, self.q, self.r, &self.coefficients, &mut result) {
            Ok(self.make_result(result))
        } else {
            Err(JsValue::from_str("Multivector is not invertible"))
        }
    }

    // ---- arithmetic ----

    pub fn add(&self, other: &WasmGenericMultivector) -> Result<WasmGenericMultivector, JsValue> {
        self.check_same_signature(other)?;
        let coeffs: Vec<f64> = self
            .coefficients
            .iter()
            .zip(&other.coefficients)
            .map(|(a, b)| a + b)
            .collect();
        Ok(self.make_result(coeffs))
    }

    pub fn sub(&self, other: &WasmGenericMultivector) -> Result<WasmGenericMultivector, JsValue> {
        self.check_same_signature(other)?;
        let coeffs: Vec<f64> = self
            .coefficients
            .iter()
            .zip(&other.coefficients)
            .map(|(a, b)| a - b)
            .collect();
        Ok(self.make_result(coeffs))
    }

    pub fn scale(&self, scalar: f64) -> WasmGenericMultivector {
        let coeffs: Vec<f64> = self.coefficients.iter().map(|c| c * scalar).collect();
        self.make_result(coeffs)
    }
}

// ========================================================================
// WasmGenericRotor
// ========================================================================

#[wasm_bindgen]
pub struct WasmGenericRotor {
    inner: WasmGenericMultivector,
    p: usize,
    q: usize,
    r: usize,
}

#[wasm_bindgen]
impl WasmGenericRotor {
    /// Create a rotor from a bivector and angle.
    ///
    /// Only supported for DIM ≤ 6 (match table).
    #[wasm_bindgen(js_name = fromBivector)]
    pub fn from_bivector(
        bivector: &WasmGenericMultivector,
        angle: f64,
    ) -> Result<WasmGenericRotor, JsValue> {
        let p = bivector.p;
        let q = bivector.q;
        let r = bivector.r;

        if !is_match_table(p, q, r) {
            return Err(JsValue::from_str(
                "Rotor creation is only supported for DIM ≤ 6 in WASM",
            ));
        }

        let half_angle_mv = bivector.scale(-angle / 2.0);
        let rotor_mv = half_angle_mv.exp()?;
        let normalized = rotor_mv.normalize()?;

        Ok(WasmGenericRotor {
            inner: normalized,
            p,
            q,
            r,
        })
    }

    /// Apply rotor to a multivector: R * v * R†
    pub fn apply(&self, mv: &WasmGenericMultivector) -> Result<WasmGenericMultivector, JsValue> {
        let r_dagger = self.inner.reverse();
        let step1 = self.inner.geometric_product(mv)?;
        step1.geometric_product(&r_dagger)
    }

    /// Compose two rotors.
    pub fn compose(&self, other: &WasmGenericRotor) -> Result<WasmGenericRotor, JsValue> {
        let composed = self.inner.geometric_product(&other.inner)?;
        let normalized = composed.normalize()?;
        Ok(WasmGenericRotor {
            inner: normalized,
            p: self.p,
            q: self.q,
            r: self.r,
        })
    }

    /// Get inverse rotor.
    pub fn inverse(&self) -> WasmGenericRotor {
        WasmGenericRotor {
            inner: self.inner.reverse(),
            p: self.p,
            q: self.q,
            r: self.r,
        }
    }
}

// ========================================================================
// Tests
// ========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ---- generic multivector: Cl(3,0,0) ----

    #[test]
    fn test_generic_new() {
        let mv = WasmGenericMultivector::new(3, 0, 0);
        assert_eq!(mv.p, 3);
        assert_eq!(mv.q, 0);
        assert_eq!(mv.r, 0);
        assert_eq!(mv.dim(), 3);
        assert_eq!(mv.basis_count(), 8);
        for i in 0..8 {
            assert_eq!(mv.get_coefficient(i), 0.0);
        }
    }

    #[test]
    fn test_generic_scalar() {
        let mv = WasmGenericMultivector::scalar(3, 0, 0, 5.0);
        assert_eq!(mv.get_coefficient(0), 5.0);
    }

    #[test]
    fn test_generic_basis_vector() {
        let e1 = WasmGenericMultivector::basis_vector(3, 0, 0, 0).unwrap();
        assert_eq!(e1.get_coefficient(1), 1.0);
    }

    #[test]
    fn test_generic_geometric_product_cl300() {
        let e1 = WasmGenericMultivector::basis_vector(3, 0, 0, 0).unwrap();
        let e2 = WasmGenericMultivector::basis_vector(3, 0, 0, 1).unwrap();
        let result = e1.geometric_product(&e2).unwrap();
        assert_eq!(result.get_coefficient(3), 1.0); // e12
    }

    #[test]
    fn test_generic_geometric_product_self_cl300() {
        let e1 = WasmGenericMultivector::basis_vector(3, 0, 0, 0).unwrap();
        let result = e1.geometric_product(&e1).unwrap();
        assert!((result.get_coefficient(0) - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_generic_outer_product() {
        let e1 = WasmGenericMultivector::basis_vector(3, 0, 0, 0).unwrap();
        let e2 = WasmGenericMultivector::basis_vector(3, 0, 0, 1).unwrap();
        let result = e1.outer_product(&e2).unwrap();
        assert_eq!(result.get_coefficient(3), 1.0);
    }

    // ---- generic multivector: Cl(2,1,0) ----

    #[test]
    fn test_generic_cl210_basis_squares() {
        let e1 = WasmGenericMultivector::basis_vector(2, 1, 0, 0).unwrap();
        let e2 = WasmGenericMultivector::basis_vector(2, 1, 0, 1).unwrap();
        let e3 = WasmGenericMultivector::basis_vector(2, 1, 0, 2).unwrap();

        let e1_sq = e1.geometric_product(&e1).unwrap();
        assert!((e1_sq.get_coefficient(0) - 1.0).abs() < 1e-10);

        let e2_sq = e2.geometric_product(&e2).unwrap();
        assert!((e2_sq.get_coefficient(0) - 1.0).abs() < 1e-10);

        let e3_sq = e3.geometric_product(&e3).unwrap();
        assert!((e3_sq.get_coefficient(0) + 1.0).abs() < 1e-10);
    }

    // ---- generic multivector: Cl(3,1,0) Minkowski ----

    #[test]
    fn test_generic_cl310_basis_squares() {
        // Cl(3,1,0): e0..e2 = space(+1), e3 = time(-1)
        let e3 = WasmGenericMultivector::basis_vector(3, 1, 0, 3).unwrap();
        let e3_sq = e3.geometric_product(&e3).unwrap();
        assert!((e3_sq.get_coefficient(0) + 1.0).abs() < 1e-10);
    }

    // ---- rotor ----

    #[test]
    fn test_generic_rotor_cl300() {
        let e1 = WasmGenericMultivector::basis_vector(3, 0, 0, 0).unwrap();
        let e2 = WasmGenericMultivector::basis_vector(3, 0, 0, 1).unwrap();
        let e12 = e1.outer_product(&e2).unwrap();

        let rotor = WasmGenericRotor::from_bivector(&e12, std::f64::consts::PI / 2.0).unwrap();
        let rotated = rotor.apply(&e1).unwrap();

        // 90° rotation: e1 → e2
        assert!(rotated.get_coefficient(2).abs() > 0.9);
    }

    // ---- signature mismatch (WASM-only: JsValue errors panic on native) ----

    #[cfg(target_arch = "wasm32")]
    #[test]
    fn test_signature_mismatch_error() {
        let mv300 = WasmGenericMultivector::new(3, 0, 0);
        let mv210 = WasmGenericMultivector::new(2, 1, 0);
        let result = mv300.geometric_product(&mv210);
        assert!(result.is_err());
    }

    // ---- fallback path (DIM > 6) ----

    #[test]
    fn test_fallback_dim7_basis_product() {
        // Cl(7,0,0) — 7D Euclidean, 128 coefficients, DIM > 6 triggers fallback
        let e1 = WasmGenericMultivector::basis_vector(7, 0, 0, 0).unwrap();
        let e2 = WasmGenericMultivector::basis_vector(7, 0, 0, 1).unwrap();

        let result = e1.geometric_product(&e2).unwrap();
        // e1 * e2 = e12 (index 3 in any metric)
        assert_eq!(result.get_coefficient(3), 1.0);
    }

    #[test]
    fn test_fallback_dim7_self_square() {
        let e1 = WasmGenericMultivector::basis_vector(7, 0, 0, 0).unwrap();
        let result = e1.geometric_product(&e1).unwrap();
        assert!((result.get_coefficient(0) - 1.0).abs() < 1e-10);
    }

    // ---- reverse and grade projection ----

    #[test]
    fn test_generic_reverse_bivector() {
        let e1 = WasmGenericMultivector::basis_vector(3, 0, 0, 0).unwrap();
        let e2 = WasmGenericMultivector::basis_vector(3, 0, 0, 1).unwrap();
        let e12 = e1.outer_product(&e2).unwrap();
        let rev = e12.reverse();
        assert!((rev.get_coefficient(3) + 1.0).abs() < 1e-10); // flips sign
    }

    #[test]
    fn test_generic_grade_projection() {
        let coeffs: Vec<f64> = vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0];
        let mv = WasmGenericMultivector::from_coefficients(3, 0, 0, &coeffs).unwrap();
        let grade1 = mv.grade_projection(1);
        assert_eq!(grade1.get_coefficient(0), 0.0);
        assert_eq!(grade1.get_coefficient(1), 2.0);
    }

    // ---- arithmetic ----

    #[test]
    fn test_generic_add() {
        let a = WasmGenericMultivector::basis_vector(3, 0, 0, 0).unwrap();
        let b = WasmGenericMultivector::basis_vector(3, 0, 0, 1).unwrap();
        let sum = a.add(&b).unwrap();
        assert_eq!(sum.get_coefficient(1), 1.0);
        assert_eq!(sum.get_coefficient(2), 1.0);
    }

    #[test]
    fn test_generic_scale() {
        let e1 = WasmGenericMultivector::basis_vector(3, 0, 0, 0).unwrap();
        let scaled = e1.scale(3.0);
        assert_eq!(scaled.get_coefficient(1), 3.0);
    }
}
